;===============================================================================
;Copyright (C) 2018 Ryan Clarke
;
;This program is free software (firmware): you can redistribute it and/or modify
;it under the terms of the GNU General Public License as published by
;the Free Software Foundation, either version 3 of the License, or
;(at your option) any later version.
;
;This program is distributed in the hope that it will be useful,
;but WITHOUT ANY WARRANTY; without even the implied warranty of
;MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;GNU General Public License for more details.
;
;You should have received a copy of the GNU General Public License
;along with this program.  If not, see <http://www.gnu.org/licenses/>.
;===============================================================================

;===============================================================================
; Program   : BIOS
; File Name : colors.inc
; Project   : v65C02 8-bit Computer
; Author    : Ryan Clarke
; E-mail    : kj6msg@icloud.com
;===============================================================================
; Release History :
;
;    Version     | Date          | Description
;    -------------------------------------------------
;    0.0         | 08/05/2018    | Initial development
;===============================================================================
; Purpose : Color constants for text attributes.
;===============================================================================


BLACK         = $00
BLUE          = $01
GREEN         = $02
CYAN          = $03
RED           = $04
MAGENTA       = $05
BROWN         = $06
LIGHT_GRAY    = $07
DARK_GRAY     = $08
LIGHT_BLUE    = $09
LIGHT_GREEN   = $0A
LIGHT_CYAN    = $0B
LIGHT_RED     = $0C
LIGHT_MAGENTA = $0D
YELLOW        = $0E
WHITE         = $0F
